### ISSUE TITLE
"Meteor" section in the README is incorrect

### ISSUE THREAD

**Issue by dandv** [Futurescaper/Futuregrapher#9]
> It is a separate Git repository, available at https://github.com/Futurescaper/Futuregrapher.

That link points to this very repo. What does "separate" refer to?

**Comment by kristiandupont** [comment]
You are right, I am not sure why I wrote that. It's removed.

**Comment by dandv** [comment]
Thanks! How reactive is the package? I'm considering it vs. wrapping [vis.js](http://visjs.org/#network).

**Comment by kristiandupont** [comment]
No problem, thank you for taking the time to look at FutureGrapher!

The package is basically plain JS network graphing library using D3, with a
very thin Meteor-wrapper. Thus, it's not reactive per se, but reactivity is
easily obtained as you just need to call .update() from some function bound
to your Meteor collection.

I am not familiar with vis.js, but a quick look at it suggests that it
supports a greater variety of visualizations like timelines. On the other
hand, FutureGrapher seems a bit more customizable given the describer*
functions-architecture where you can affect rendering of your viz with
callbacks rather than just plain options.
